"""Shared GPR theme codes for the scorer and news NLP extractors."""

TIER1_CODES = (
    "ARMEDCONFLICT", "TERROR_ATTACK", "INVASION", "COUP",
    "ETHNIC_VIOLENCE", "GENOCIDE", "NUCLEAR_WEAPONS",
    "CHEMICAL_WEAPONS", "BIOLOGICAL_WEAPONS",
)
TIER2_CODES = (
    "TERROR", "TAX_FNCACT_MILITARY", "TAX_FNCACT_SOLDIER", "TAX_FNCACT_REBEL",
    "TAX_FNCACT_TERRORIST", "SANCTION", "NUCLEAR", "DIPLOMATIC_CRISIS",
    "BLOCKADE", "BORDER_DISPUTE", "MARITIME_DISPUTE", "PROXY_WAR",
    "BALLISTIC_MISSILES",
)
TIER3_CODES = ("ESPIONAGE", "CYBERATTACK", "WAR_CRIME")
